(ns p1b-removens)
;; PROBE 2b: remove-ns then recovery paths; eval under binding *ns*; eval of ns form string.
(def dir "/home/klein/.claude/jobs/9d0c3547/tmp/reload-probe/src/probe/")
(defn show [label thunk]
  (println (str "  " label " => "
                (try (pr-str (thunk))
                     (catch #?(:clj Exception :default :default) e (str "THREW " (ex-message e)))))))
(defn write-a! [tag]
  (spit (str dir "a.cljc")
        (str "(ns probe.a)\n(println \"  [loading probe.a " tag "]\")\n(defn f [x] [:" tag " x])\n(defn g [x] (f x))\n")))
(write-a! "v1")
(spit (str dir "b.cljc") "(ns probe.b (:require [probe.a :as a]))\n(defn call-f [x] (a/f x))\n")
(require 'probe.b)
(def cap-var #'probe.a/f)
(def tool-clos {:handler (fn [x] (probe.a/f x))})
(show "before: probe.b/call-f" #(probe.b/call-f 1))
(show "remove-ns probe.a" #(remove-ns 'probe.a))
(write-a! "v8")
(show "require after remove-ns (does it reload?)" #(require 'probe.a))
(show "probe.a/f after require" #(probe.a/f 1))
(show "load-file after remove-ns" #(load-file (str dir "a.cljc")))
(show "probe.a/f" #(probe.a/f 1))
(show "probe.a/g" #(probe.a/g 1))
(show "probe.b/call-f (alias a -> probe.a, ns object replaced)" #(probe.b/call-f 1))
(show "tool-clos :handler (names probe.a/f)" #((:handler tool-clos) 1))
(show "cap-var (#'f from the REMOVED ns)" #(cap-var 1))
(show "identical? cap-var #'probe.a/f" #(identical? cap-var #'probe.a/f))
(show "load-file b.cljc, then probe.b/call-f" #(do (load-file (str dir "b.cljc")) (probe.b/call-f 1)))

(println "-- eval under (binding [*ns* ...])")
(show "binding *ns* + eval defn" #(binding [*ns* (find-ns 'probe.a)] (eval '(defn h [x] [:h x]))))
(show "resolve p1b-removens/h" #(resolve 'p1b-removens/h))
(show "resolve probe.a/h" #(resolve 'probe.a/h))
(println "-- eval of a whole (ns ...) + defs as one read (do ...) string")
(show "eval (do (ns probe.c) (defn k [] :k1))"
      #(eval (read-string "(do (ns probe.c) (defn k [] :k1))")))
(show "current *ns* after that eval" #(str *ns*))
(in-ns 'p1b-removens)
(show "probe.c/k" #((resolve 'probe.c/k)))
(println "-- read-string of multiple forms: only the first is read")
(show "read-string \"(def x1 1) (def x2 2)\"" #(read-string "(def x1 1) (def x2 2)"))
