(ns p5b-collide
  (:require [hive-addon.protocol :as p]))
;; PROBE 5b: (a) same record NAME in two addon namespaces; (b) defmethods owned by
;; another ns after defmulti owner reload; (c) load-file ns leak and binding *ns*.

(def dir "/home/klein/.claude/jobs/9d0c3547/tmp/reload-probe/src/probe/")
(defn show [label thunk]
  (println (str "  " label " => "
                (try (pr-str (thunk))
                     (catch #?(:clj Exception :default :default) e (str "THREW " (ex-message e)))))))

(println "== (a) two addons, both (defrecord Addon ...), different namespaces")
(spit (str dir "x.cljc")
      "(ns probe.x (:require [hive-addon.protocol :as p]))\n(defrecord Addon [] p/IAddon (addon-id [_] \"x\") (health [_] {:who :x}))\n(defn make [] (->Addon))\n")
(spit (str dir "y.cljc")
      "(ns probe.y (:require [hive-addon.protocol :as p]))\n(defrecord Addon [] p/IAddon (addon-id [_] \"y\") (health [_] {:who :y}))\n(defn make [] (->Addon))\n")
(require 'probe.x)
(def x1 (probe.x/make))
(show "x1 addon-id (only probe.x loaded)" #(p/addon-id x1))
(require 'probe.y)
(def y1 (probe.y/make))
(show "x1 addon-id (after probe.y loaded)" #(p/addon-id x1))
(show "y1 addon-id" #(p/addon-id y1))
(show "x1 health / y1 health" #(vector (p/health x1) (p/health y1)))
(show "types" #(vector (type x1) (type y1) (= (type x1) (type y1))))
(show "(instance? (type y1) x1)" #(instance? (type y1) x1))
(show "(= x1 y1)" #(= x1 y1))
(show "fresh (probe.x/make) addon-id" #(p/addon-id (probe.x/make)))

(println "== (a2) same record name, only ONE implements the protocol")
(spit (str dir "u.cljc")
      "(ns probe.u (:require [hive-addon.protocol :as p]))\n(defrecord Thing [] p/IAddon (addon-id [_] \"u\"))\n")
(spit (str dir "w.cljc") "(ns probe.w)\n(defrecord Thing [])\n")
(require 'probe.u)
(require 'probe.w)
(show "(satisfies? p/IAddon (probe.w/->Thing)) [w's Thing implements nothing]" #(satisfies? p/IAddon (probe.w/->Thing)))
(show "(p/addon-id (probe.w/->Thing))" #(p/addon-id (probe.w/->Thing)))

(println "== (b) defmulti owner reload vs defmethods contributed by another ns")
(spit (str dir "host_m.cljc") "(ns probe.host-m)\n(defmulti render :op)\n(defmethod render :default [m] [:host-default m])\n")
(spit (str dir "plug_m.cljc") "(ns probe.plug-m (:require [probe.host-m :as h]))\n(defmethod h/render :ui/show-panel [m] [:plugin-panel m])\n")
(require 'probe.plug-m)
(show "render :ui/show-panel (plugin method)" #(probe.host-m/render {:op :ui/show-panel}))
(show "load-file host_m.cljc (owner reload)" #(load-file (str dir "host_m.cljc")))
(in-ns 'p5b-collide)
(show "render :ui/show-panel after OWNER reload" #(probe.host-m/render {:op :ui/show-panel}))
(show "load-file plug_m.cljc (plugin reload)" #(load-file (str dir "plug_m.cljc")))
(in-ns 'p5b-collide)
(show "render :ui/show-panel after plugin reload" #(probe.host-m/render {:op :ui/show-panel}))

(println "== (c) load-file ns leak; does (binding [*ns* ...]) contain it?")
(spit (str dir "q.cljc") "(ns probe.q)\n(def q 1)\n")
(show "*ns* before" #(str *ns*))
(show "binding [*ns* *ns*] load-file" #(binding [*ns* *ns*] (load-file (str dir "q.cljc"))))
(show "*ns* after binding+load-file" #(str *ns*))
(def landed-1 1)
(show "resolve p5b-collide/landed-1 (def after binding+load-file)" #(resolve 'p5b-collide/landed-1))
(show "bare load-file" #(load-file (str dir "q.cljc")))
(show "*ns* after bare load-file" #(str *ns*))
