(require '[demo.addon :as a])
(println "first:" (a/greet))
(spit "src/demo/addon.cljc" "(ns demo.addon)\n(defn greet [] \"v2\")\n")
(println "require again (no reload):" (do (require '[demo.addon :as a]) (a/greet)))
(println "require :reload ->" (try (require '[demo.addon :as a] :reload) :ok (catch Exception e (str "ERR " e))))
(load-file "src/demo/addon.cljc")
(println "after load-file:" (a/greet))
(println "ns now:" (str *ns*))
(defn caller [] (a/greet))
(dotimes [_ 3000] (caller))
(spit "src/demo/addon.cljc" "(ns demo.addon)\n(defn greet [] \"v3\")\n")
(load-file "src/demo/addon.cljc")
(println "hot caller after 3000 calls + reload:" (caller))
