(ns user)
(spit "src/demo/addon.cljc" "(ns demo.addon)\n(defn greet [] \"v1\")\n")
(require '[demo.addon :as a])
(println "first:" (demo.addon/greet))
(spit "src/demo/addon.cljc" "(ns demo.addon)\n(defn greet [] \"v2\")\n")
(println "require again (no reload):" (do (require '[demo.addon :as a]) (demo.addon/greet)))
(load-file "src/demo/addon.cljc")
(println "ns after load-file:" (str *ns*))
(in-ns 'user)
(println "after load-file:" (demo.addon/greet))
(defn caller [] (demo.addon/greet))
(dotimes [_ 5000] (caller))
(spit "src/demo/addon.cljc" "(ns demo.addon)\n(defn greet [] \"v3\")\n")
(load-file "src/demo/addon.cljc")
(in-ns 'user)
(println "hot caller after 5000 calls + reload:" (caller))
(defprotocol P (hello [this]))
(spit "src/demo/rec.cljc" "(ns demo.rec)\n(defrecord R [] user/P (hello [_] \"rec-v1\"))\n")
(load-file "src/demo/rec.cljc")
(in-ns 'user)
(def r1 (demo.rec/->R))
(spit "src/demo/rec.cljc" "(ns demo.rec)\n(defrecord R [] user/P (hello [_] \"rec-v2\"))\n")
(load-file "src/demo/rec.cljc")
(in-ns 'user)
(println "old instance:" (hello r1) " new instance:" (hello (demo.rec/->R)))
